/**
 * This class contains the tracecodes used throughout the application
 */

const tracecodes = {
    AUTHENTICATION_REQUEST           : 'AUTHENTICATION_REQUEST',
    TRUELAYER_AUTH_URL               : 'TRUELAYER_AUTH_URL',
    AUTH_CALLBACK_REQUEST            : 'AUTH_CALLBACK_REQUEST',
    AUTH_CALLBACK_ERROR              : 'AUTH_CALLBACK_ERROR',
    APP_AUTH_TOKEN_GENERATED         : 'APP_AUTH_TOKEN_GENERATED',
    APP_AUTH_TOKEN_GENERATION_FAILED : 'APP_AUTH_TOKEN_GENERATION_FAILED',
    AUTHENTICATED_CUSTOMER_INFO      : 'AUTHENTICATED_CUSTOMER_INFO',
    AUTHENTICATION_VIA_MIDDLEWARE    : 'AUTHENTICATION_VIA_MIDDLEWARE',
    USER_NOT_FOUND                   : 'USER_NOT_FOUND',
    AUTHENTICATED_USER_FOUND         : 'AUTHENTICATED_USER_FOUND',
    EXPIRED_ACCESS_TOKEN             : 'EXPIRED_ACCESS_TOKEN',
    ACCESS_TOKEN_RENEWAL_SUCCESS     : 'ACCESS_TOKEN_RENEWAL_SUCCESS',
    ACCESS_TOKEN_RENEWAL_FAILURE     : 'ACCESS_TOKEN_RENEWAL_FAILURE',
    CUSTOMER_TRANSACTIONS_REQUEST    : 'CUSTOMER_TRANSACTIONS_REQUEST',
    CUSTOMER_TRANSACTIONS_RESPONSE   : 'CUSTOMER_TRANSACTIONS_RESPONSE',
    CUSTOMER_ACCOUNT_STATS_REQUEST   : 'CUSTOMER_ACCOUNT_STATS_REQUEST',
    CUSTOMER_ACCOUNT_STATS_RESPONSE  : 'CUSTOMER_ACCOUNT_STATS_RESPONSE',
    CUSTOMER_TRANSCTIONS_NOT_SAVED   : 'CUSTOMER_TRANSCTIONS_NOT_SAVED',
    AUTH_TOKEN_GENERATION_REQUEST    : 'AUTH_TOKEN_GENERATION_REQUEST',
    SAVE_TRANSACTIONS_REQUEST        : 'SAVE_TRANSACTIONS_REQUEST',
    FIND_USER_BY_TOKEN_REQUEST       : 'FIND_USER_BY_TOKEN_REQUEST',
    DB_CONNECTION_REQUEST            : 'DB_CONNECTION_REQUEST',
}

module.exports ={tracecodes};
